### ISSUE TITLE
Evaluation phase results

### ISSUE THREAD

**Issue by AlexCrosby** [AliOsm/AI-SOCO#2]
Will the ongoing results for the evaluation phase be made publicly visible? 

I'm doing my thesis on this project so ideally I would like to be able to know how well I have done vs other users, but it's due before the end of the evaluation phase.

**Comment by AliOsm** [comment]
We are discussing this now, we will get back to you ASAP.

**Comment by AliOsm** [comment]
Hello @AlexCrosby,

Thank you for your interest and participation in our task. We discussed your request and agreed to publish the evaluation phase results after the deadline (Sep 7). In the meantime, please, feel free to use the development set results in your thesis. Since the dataset was randomly split into training/development/testing sets, we expect the results to be very close.

Thank you again and we hope the best for you!
